version: '3.7'

services:

  image-library:
    image: image-library
    build: .
    environment:
      NODE_ENV: production
    volumes:
      - ./upload:/app/upload
    ports:
      - 8789:3000
    restart: always
